### ISSUE TITLE
Receiving error handle not initialized from Rooms to HBZones component

### ISSUE THREAD

**Issue by antonszilasi** [ladybug-analysis-tools/honeybeex#18]
I am receiving the error seen in the picture 

![error not initialized](https://cloud.githubusercontent.com/assets/8773483/17046727/114dd4ee-4f9c-11e6-82bf-ef753bdfde06.JPG)

The full error is:

ERROR:
Handle is not initialized.

Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "C:\Users\szilasia\AppData\Roaming\Dynamo\Dynamo Revit\1.1\packages\Honeybee\extra\honeybeex\revit.py", line 246, in convertRoomsToHBZones
    _hbSurface = HBSurface("%s:%s" % (_zone.name, createUUID()),
  File "C:\Users\szilasia\AppData\Roaming\Dynamo\Dynamo Revit\1.1\packages\Honeybee\extra\honeybeex\hbsurface.py", line 38, in __init__
    AnalysisSurface.__init__(
  File "C:\Program Files (x86)\IronPython 2.7\Lib\abc.py", line 151, in __subclasscheck__
    if subclass in cls._abc_cache:
  File "C:\Program Files (x86)\IronPython 2.7\Lib\_weakrefset.py", line 73, in __contains__
    return wr in self.data
SystemError: Handle is not initialized.

The Revit file can be found at: https://app.box.com/s/77xw13jycu96mk6amtesmzzw96qnjfe2

**Comment by mostaphaRoudsari** [comment]
@antonszilasi this is a dynamo issue. Restarting the file should solve the problem.
